# Generated by Django 4.2.11 on 2024-03-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refuels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuelsession',
            name='litres_filled',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
