# Generated by Django 5.0.3 on 2024-04-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refuels', '0002_alter_refuelsession_litres_filled'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='refuelsession',
            table='refuels',
        ),
    ]
